#!/bin/sh
#
# This script executes zsh with this checkout's dotfiles. Use it to develop and
# test changes in multiple clones.
set -o errexit

ZDOTDIR="$(cd "$(dirname "$0")/.." && pwd -P)" exec zsh "$@"
